# Site settings
title: First RP Church
email: thomas@thomaswoltjer.com
description: > 
  First Reformed Presbyterian Church of Grand Rapids is a congregation of the RPCNA located in Grand Rapids, MI. It is led by Pastor Craig Scott and is welcoming to all visitors.
baseurl: ''
url: 'http://firstrpc.org' 

# Build settings
markdown: kramdown
theme: minima
